# Generated by Django 2.2.7 on 2019-11-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nro_documento', models.CharField(max_length=50)),
                ('fec_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('foto', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('C', 'Cellular'), ('F', 'Fijo')], default='C', max_length=1)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=50)),
                ('tarifa_aprox', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.TipoDocumento'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_cont', models.DateTimeField()),
                ('comentario', models.CharField(max_length=100)),
                ('calificacion', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('N', 'Negocioacion'), ('A', 'Anulado')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Ciudad')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Distrito')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Pais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Persona')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Persona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='codigo_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Pais', to_field='codigo'),
        ),
        migrations.CreateModel(
            name='Proveedor_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Proveedor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Servicio')),
            ],
            options={
                'unique_together': {('proveedor', 'servicio')},
            },
        ),
    ]
