# Generated by Django 2.2.7 on 2019-12-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpersgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_documento',
        ),
    ]
