# Generated by Django 2.2.7 on 2019-11-28 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpersgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_cont', models.DateTimeField()),
                ('comentario', models.CharField(max_length=100)),
                ('calificacion', models.SmallIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpersgo.Proveedor')),
            ],
        ),
    ]
